# Generated by Django 2.1.3 on 2018-11-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20181115_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentary',
            new_name='content',
        ),
    ]
